name: Deploy site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  deploy-api-docs:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Install packages
        working-directory: .
        run: |
          npm install
      - name: Download Ceramic
        working-directory: .
        run: |
          node download-ceramic.js
      - name: Install Ceramic
        working-directory: ceramic/tools
        run: |
          ./ceramic link
      - name: Generate API Docs
        working-directory: .
        run: |
          ./gen-docs.sh
      - name: Add .nojekyll
        working-directory: .
        run: |
          touch docs/.nojekyll
      - name: Deploy to Github Pages
        uses: ceramic-engine/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: docs
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
