name: Deploy site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  deploy-api-docs:
    runs-on: macos-10.15
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Install packages
        working-directory: .
        run: |
          npm install
      - name: Download Ceramic
        working-directory: .
        run: |
          node download-ceramic.js
      - name: Install Ceramic
        working-directory: ceramic/tools
        run: |
          ./ceramic link
      - name: Generate API Docs
        working-directory: .
        run: |
          ./gen-docs.sh
